apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podnetworkings.vpc.uk8s.ucloud.cn
spec:
  group: vpc.uk8s.ucloud.cn
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                securityGroupIds:
                  type: array
                  items:
                    type: string
                subnetIds:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                status:
                  type: string
  scope: Cluster
  names:
    plural: podnetworkings
    singular: podnetworking
    kind: PodNetworking
---
