name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      build-cnivpc:
        description: 'Build cnivpc'
        type: boolean
        default: true

      build-ipamd:
        description: 'Build ipamd'
        type: boolean
        default: true

      build-vip-controller:
        description: 'Build vip-controller'
        type: boolean
        default: true

      image-tag:
        description: 'Image tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to UHub
      uses: docker/login-action@v2
      with:
        registry: uhub.service.ucloud.cn
        username: ${{ secrets.UHUB_USER }}
        password: ${{ secrets.UHUB_PASSWORD }}

    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5

    - name: Build cnivpc
      if: ${{ inputs.build-cnivpc }}
      run: IMAGE_TAG="${{ inputs.image-tag }}" make cnivpc

    - name: Build ipamd
      if: ${{ inputs.build-ipamd }}
      run: IMAGE_TAG="${{ inputs.image-tag }}" make ipamd

    - name: Build vip-controller
      if: ${{ inputs.build-vip-controller }}
      run: IMAGE_TAG="${{ inputs.image-tag }}" make vip-controller
